add stalls into individual hawker centers
DigitalKampong/dk-frontend pull request #9
Opened 2021-01-08 18:38 UTC by yixin567

I have added the stalls into the individual hawker centers page.

2021-01-09 03:16 UTC, Kalsyc requested changes
Looks good. However, can we make the font-size a bit larger?
Actually, we might have to use em/rem sizing soon instead of pure px for some of the stuff (especially if we need to shift to a mobile-first design)

2021-01-09 09:48 UTC, niqiukun commented
> Actually, we might have to use em/rem sizing soon instead of pure px for some of the stuff (especially if we need to shift to a mobile-first design)

No need to worry about that first. There should be a way to convert all px to rem automatically. Actually for now all the pages / components I write, I strictly follow the values from the wire frame (`font-family`, `font-size`, `line-height`). Feel like we should standardize and extract a few text types as mixins to use in different places.

2021-01-10 12:07 UTC, Kalsyc commented
> > Actually, we might have to use em/rem sizing soon instead of pure px for some of the stuff (especially if we need to shift to a mobile-first design)
> 
> No need to worry about that first. There should be a way to convert all px to rem automatically. Actually for now all the pages / components I write, I strictly follow the values from the wire frame (`font-family`, `font-size`, `line-height`). Feel like we should standardize and extract a few text types as mixins to use in different places.

Yeah, we need to standardize somehow. I'm not sure how they wanna proceed with the responsive design for mobile...

2021-01-17 09:04 UTC, Kalsyc approved these changes

2021-01-17 09:05 UTC, merged